recorder:
  camera_index: 0            # which camera to use
  fps: 30                    # target capture fps
  resolution:
    width: 1280
    height: 720
  image_format: "jpg"        # jpg / png
  output_dir: "./frames"     # where to store raw frames
  buffer_size: 100           # max number of frames in memory buffer
  keep_disk_copy: false      # whether to save every frame to disk or not
