# Detector Configuration File

# Model Configuration
model:
  onnx_file: "model.onnx"
  img_size: 640
  conf_thres: 0.6
  device: "cpu"  # Options: "cpu", "gpu"

# File Paths
paths:
  categories_file: "categories.yaml"
  default_image: "./default/default_img.jpg"

# Inference Settings
inference:
  batch_size: 1
  max_detections: 100

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true

# CLO Processing
clo:
  enabled: true
  values_file: "clo_values.yaml"

# Logging
logging:
  level: "INFO"
  enable_console: true
  enable_file: false

# Save Detection Results
save_results:
  enabled: true
  output_dir: "detections"
